export const PROVINCIAS = [
    '',
    'ÁLAVA',
    'ALBACETE',
    'ALICANTE',
    'ALMERÍA',
    'ÁVILA',
    'BADAJOZ',
    'BALEARES',
    'BARCELONA',
    'BURGOS',
    'CÁCERES',
    'CÁDIZ',
    'CASTELLÓN',
    'CIUDAD REAL',
    'CÓRDOBA',
    'CORUÑA',
    'CUENCA',
    'GERONA',
    'GRANADA',
    'GUADALAJARA',
    'GUIPÚZCOA',
    'HUELVA',
    'HUESCA',
    'JAÉN',
    'LEÓN',
    'LÉRIDA',
    'LA RIOJA',
    'LUGO',
    'MADRID',
    'MÁLAGA',
    'MURCIA',
    'NAVARRA',
    'ORENSE',
    'ASTURIAS',
    'PALENCIA',
    'LAS PALMAS',
    'PONTEVEDRA',
    'SALAMANCA',
    'STA CRUZ TENERIFE',
    'CANTABRIA',
    'SEGOVIA',
    'SEVILLA',
    'SORIA',
    'TARRAGONA',
    'TERUEL',
    'TOLEDO',
    'VALENCIA',
    'VALLADOLID',
    'VIZCAYA',
    'ZAMORA',
    'ZARAGOZA',
    'CEUTA',
    'MELILLA',
];

